// <auto-generated />
using Intex2026.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Intex2026.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("Intex2026.Models.Donation", b =>
                {
                    b.Property<int>("DonationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CampaignName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByPartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("DonationDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DonationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EstimatedValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImpactUnit")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReferralPostId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupporterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DonationId");

                    b.HasIndex("SupporterId");

                    b.ToTable("Donations", (string)null);
                });

            modelBuilder.Entity("Intex2026.Models.DonationAllocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllocationDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AllocationNotes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountAllocated")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DonationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProgramArea")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AllocationId");

                    b.HasIndex("DonationId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("DonationAllocations", (string)null);
                });

            modelBuilder.Entity("Intex2026.Models.EducationRecord", b =>
                {
                    b.Property<int>("EducationRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AttendanceRate")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("CompletionStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnrollmentStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ProgressPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("RecordDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchoolName")
                        .HasColumnType("TEXT");

                    b.HasKey("EducationRecordId");

                    b.HasIndex("ResidentId");

                    b.ToTable("EducationRecords", (string)null);
                });

            modelBuilder.Entity("Intex2026.Models.HealthWellbeingRecord", b =>
                {
                    b.Property<int>("HealthRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Bmi")
                        .HasColumnType("decimal(4,2)");

                    b.Property<bool>("DentalCheckupDone")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("EnergyLevelScore")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal?>("GeneralHealthScore")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("MedicalCheckupDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NutritionScore")
                        .HasColumnType("decimal(3,2)");

                    b.Property<bool>("PsychologicalCheckupDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecordDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("SleepQualityScore")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("HealthRecordId");

                    b.HasIndex("ResidentId");

                    b.ToTable("HealthWellbeingRecords", (string)null);
                });

            modelBuilder.Entity("Intex2026.Models.HomeVisitation", b =>
                {
                    b.Property<int>("VisitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoordinationKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyCooperationLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyMembersPresent")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FollowUpNeeded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FollowUpNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationVisited")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observations")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SafetyConcernsNoted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SocialWorker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitOutcome")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VisitationId");

                    b.HasIndex("ResidentId");

                    b.ToTable("HomeVisitations", (string)null);
                });

            modelBuilder.Entity("Intex2026.Models.InKindDonationItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DonationId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EstimatedUnitValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IntendedUse")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceivedCondition")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("DonationId");

                    b.ToTable("InKindDonationItems", (string)null);
                });

            modelBuilder.Entity("Intex2026.Models.IncidentReport", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FollowUpRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IncidentDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResolutionDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Resolved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseTaken")
                        .HasColumnType("TEXT");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IncidentId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("IncidentReports", (string)null);
                });

            modelBuilder.Entity("Intex2026.Models.InterventionPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaseConferenceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanDescription")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServicesProvided")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlanId");

                    b.HasIndex("ResidentId");

                    b.ToTable("InterventionPlans", (string)null);
                });

            modelBuilder.Entity("Intex2026.Models.Partner", b =>
                {
                    b.Property<int>("PartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartnerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartnerType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PartnerId");

                    b.ToTable("Partners", (string)null);
                });

            modelBuilder.Entity("Intex2026.Models.PartnerAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignmentEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignmentStart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProgramArea")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsibilityNotes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AssignmentId");

                    b.HasIndex("PartnerId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("PartnerAssignments", (string)null);
                });

            modelBuilder.Entity("Intex2026.Models.ProcessRecording", b =>
                {
                    b.Property<int>("RecordingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ConcernsFlagged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmotionalStateEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmotionalStateObserved")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FollowUpActions")
                        .HasColumnType("TEXT");

                    b.Property<string>("InterventionsApplied")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ProgressNoted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReferralMade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SessionDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionNarrative")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialWorker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RecordingId");

                    b.HasIndex("ResidentId");

                    b.ToTable("ProcessRecordings", (string)null);
                });

            modelBuilder.Entity("Intex2026.Models.PublicImpactSnapshot", b =>
                {
                    b.Property<int>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Headline")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetricPayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryText")
                        .HasColumnType("TEXT");

                    b.HasKey("SnapshotId");

                    b.ToTable("PublicImpactSnapshots", (string)null);
                });

            modelBuilder.Entity("Intex2026.Models.Resident", b =>
                {
                    b.Property<int>("ResidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgeUponAdmission")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedSocialWorker")
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseControlNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentRiskLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateCaseStudyPrepared")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateClosed")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateColbObtained")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateColbRegistered")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateEnrolled")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateOfAdmission")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("FamilyIndigenous")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FamilyInformalSettler")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FamilyIs4ps")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FamilyParentPwd")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FamilySoloParent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasSpecialNeeds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InitialCaseAssessment")
                        .HasColumnType("TEXT");

                    b.Property<string>("InitialRiskLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPwd")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LengthOfStay")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("PresentAge")
                        .HasColumnType("TEXT");

                    b.Property<string>("PwdType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferralSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferringAgencyPerson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReintegrationStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReintegrationType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Religion")
                        .HasColumnType("TEXT");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialNeedsDiagnosis")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SubCatAtRisk")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SubCatChildLabor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SubCatChildWithHiv")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SubCatCicl")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SubCatOrphaned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SubCatOsaec")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SubCatPhysicalAbuse")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SubCatSexualAbuse")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SubCatStreetChild")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SubCatTrafficked")
                        .HasColumnType("INTEGER");

                    b.HasKey("ResidentId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("Residents", (string)null);
                });

            modelBuilder.Entity("Intex2026.Models.Safehouse", b =>
                {
                    b.Property<int>("SafehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacityGirls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacityStaff")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentOccupancy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SafehouseCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SafehouseId");

                    b.ToTable("Safehouses", (string)null);
                });

            modelBuilder.Entity("Intex2026.Models.SafehouseMonthlyMetric", b =>
                {
                    b.Property<int>("MetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveResidents")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AvgEducationProgress")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("AvgHealthScore")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("HomeVisitationCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IncidentCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MonthEnd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MonthStart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessRecordingCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MetricId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("SafehouseMonthlyMetrics", (string)null);
                });

            modelBuilder.Entity("Intex2026.Models.SocialMediaPost", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AvgViewDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BoostBudgetPhp")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("CallToActionType")
                        .HasColumnType("TEXT");

                    b.Property<string>("CampaignName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Caption")
                        .HasColumnType("TEXT");

                    b.Property<int>("CaptionLength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClickThroughs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Comments")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentTopic")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("TEXT");

                    b.Property<int>("DonationReferrals")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EngagementRate")
                        .HasColumnType("decimal(8,6)");

                    b.Property<decimal>("EstimatedDonationValuePhp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("FeaturesResidentStory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FollowerCountAtPost")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Forwards")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasCallToAction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hashtags")
                        .HasColumnType("TEXT");

                    b.Property<int>("Impressions")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBoosted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Likes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaType")
                        .HasColumnType("TEXT");

                    b.Property<int>("MentionsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumHashtags")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformPostId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PostHour")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileVisits")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reach")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Saves")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SentimentTone")
                        .HasColumnType("TEXT");

                    b.Property<int>("Shares")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubscriberCountAtPost")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VideoViews")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WatchTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("PostId");

                    b.ToTable("SocialMediaPosts", (string)null);
                });

            modelBuilder.Entity("Intex2026.Models.Supporter", b =>
                {
                    b.Property<int>("SupporterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcquisitionChannel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstDonationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupporterType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SupporterId");

                    b.ToTable("Supporters", (string)null);
                });

            modelBuilder.Entity("Intex2026.Models.Donation", b =>
                {
                    b.HasOne("Intex2026.Models.Supporter", "Supporter")
                        .WithMany()
                        .HasForeignKey("SupporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supporter");
                });

            modelBuilder.Entity("Intex2026.Models.DonationAllocation", b =>
                {
                    b.HasOne("Intex2026.Models.Donation", "Donation")
                        .WithMany()
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Intex2026.Models.Safehouse", "Safehouse")
                        .WithMany()
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Donation");

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("Intex2026.Models.EducationRecord", b =>
                {
                    b.HasOne("Intex2026.Models.Resident", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Intex2026.Models.HealthWellbeingRecord", b =>
                {
                    b.HasOne("Intex2026.Models.Resident", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Intex2026.Models.HomeVisitation", b =>
                {
                    b.HasOne("Intex2026.Models.Resident", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Intex2026.Models.InKindDonationItem", b =>
                {
                    b.HasOne("Intex2026.Models.Donation", "Donation")
                        .WithMany()
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donation");
                });

            modelBuilder.Entity("Intex2026.Models.IncidentReport", b =>
                {
                    b.HasOne("Intex2026.Models.Resident", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Intex2026.Models.Safehouse", "Safehouse")
                        .WithMany()
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resident");

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("Intex2026.Models.InterventionPlan", b =>
                {
                    b.HasOne("Intex2026.Models.Resident", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Intex2026.Models.PartnerAssignment", b =>
                {
                    b.HasOne("Intex2026.Models.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Intex2026.Models.Safehouse", "Safehouse")
                        .WithMany()
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Partner");

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("Intex2026.Models.ProcessRecording", b =>
                {
                    b.HasOne("Intex2026.Models.Resident", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Intex2026.Models.Resident", b =>
                {
                    b.HasOne("Intex2026.Models.Safehouse", "Safehouse")
                        .WithMany()
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("Intex2026.Models.SafehouseMonthlyMetric", b =>
                {
                    b.HasOne("Intex2026.Models.Safehouse", "Safehouse")
                        .WithMany()
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Safehouse");
                });
#pragma warning restore 612, 618
        }
    }
}
